#Here we put the specific products we would like to track
#The variable is a list with tuples
# The first element in the tuple is a list of keyword/s that should be in the text of the product in order to match
# The second element is optional (it can not be present) and is a list that contains words that the product shouldnt have in its description.

CONDITIONS_JSON_NACHO = [
(['nesquick', '0%'],),
(['gullon','sin azucares'],['yogur','de fibra','tostada']),
(['papel de cocina'],),
(['papel higienico'], ['humedo']),
(['copos de maiz','el corte ingles'],),
(['weetabix'],),
(['huevos', 'clase'],),
(['arroz integral', '1 kg'],),
(['ravioli'],),
(['tomate triturado'],),
(['harina integral'], ['bolsa','galle', 'soria']),
(['santiveri','galletas','0% azu'],),
(['tofu ahumado', 'el corte ingles'],),
(['fairy','original','pastilla'],),
(['alpro','sin azucar','400 g'],),
(['atun claro','natural','lata'],),
(['pechuga de pollo'],['lonchas', 'filteteada', 'campofrio', 'empanada', 'tiras', 'caseritos', 'rebozados', 'la cocinera', 'fripozo', 'al curry', 'fajitas', 'braseada', 'en aceite', 'asada', 'latas']),
(['coosur aceite de oliva virgen extra','arbequina'],),
(['aceite refinado de girasol','borges'],),
(['papel de aluminio'],),
(['espinaca','bolsa','el corte ingles'], ['salteado','brotes']),
(['harina de avena'],),
(['chocolate negro', '80%','tableta'],),
(['chocolate negro', '90%','tableta'],),
(['chocolate negro', '85%','tableta'],),
(['chocolate negro', '80 %','tableta'],),
(['chocolate negro', '90 %','tableta'],),
(['chocolate negro', '85 %','tableta'],),
(['suavizante', 'concentrado','botella'], ['champu','pelo','cabello','gel intimo']),
(['quitamanchas','para ropa'],['capsulas']),
(['detergente','para ropa'],['capsulas'])
]


CONDITIONS_JSON_JOSE = [
(['gullon','sin azucares'],),
(['papel de cocina'],),
(['papel higienico'], ['humedo']),
(['copos de maiz','el corte ingles'],),
(['weetabix'],),
(['huevos', 'clase'],),
(['arroz integral', '1 kg'],),
(['ravioli'],),
(['tomate triturado'],),
(['harina integral'], ['bolsa','galle', 'soria']),
(['grana padano'], ['garofalo', 'pizza']),
(['santiveri','galletas','0% azu'],),
(['tofu ahumado', 'el corte ingles'],),
(['fairy','original','pastilla'],),
(['alpro','sin azucar','400 g'],),
(['atun claro','natural','lata'],),
(['pechuga de pollo'],['lonchas', 'filteteada', 'campofrio', 'empanada', 'tiras', 'caseritos', 'rebozados', 'la cocinera', 'fripozo', 'al curry', 'fajitas', 'braseada', 'en aceite', 'asada', 'latas']),
(['coosur aceite de oliva virgen extra','arbequina'],),
(['aceite refinado de girasol','borges'],),
(['papel de aluminio'],),
(['espinaca','bolsa','el corte ingles'], ['salteado','brotes']),
(['harina de avena'],),
(['chocolate negro', '80%','tableta'],),
(['chocolate negro', '90%','tableta'],),
(['chocolate negro', '85%','tableta'],),
(['chocolate negro', '80 %','tableta'],),
(['chocolate negro', '90 %','tableta'],),
(['chocolate negro', '85 %','tableta'],),
(['suavizante', 'concentrado','botella'], ['champu','pelo','cabello','gel intimo']),
(['quitamanchas','para ropa'],['capsulas']),
(['detergente','para ropa'],['capsulas']),
(['pañales','dodot'],),
(['nutella'],['galletas']),
(['philadelphia','queso'],['fridela','maheso']),
(['leche', 'sin lactosa', '1 l'],['soja','almendra','coco','chocolate']),
(['chocolate', 'torras'],),
(['mousse', 'vitalinea'],),
(['masa', 'buitoni'],),
(['tostados', 'schar'],),
(['tostadas', 'recondo'],),
(['sanavi', 'galletas con salvado'],),
(['arroz', 'vaporizado'],)
]
